# 1. Database name
spring.cloud.gcp.sql.database-name=users-db

# 2. The specific instance "Link" (Instance Connection Name)
spring.cloud.gcp.sql.instance-connection-name=numeric-chassis-487900-m0:us-central1:testingdb

# 3. Credentials (Use variables so you can inject them in Cloud Run)
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

